### PR TITLE
Agrelon updates

### PR DESCRIPTION
**Pull request by cyocum**
Updated the below to use agrelon in addition to the rel ontology

./LL/cairpri_móir.trig
./LL/ceniuil_ennai.trig
./LL/aisneidem_di_araill.trig
./LL/ceniuil_lugdach.trig
./LL/cenel_n_eithne.trig

### CODE REVIEW

**Review by Eystein-Thanisch — COMMENTED** [review]
Thanks for this. I don't feel able to Approve or Request Changes, as I don't know what Agrelon is meant to look like. All I can say is that this all looks internally consistent and it seems to be passing the checks. 

Did the new triples etc. all need to be added manually? If so, we should consider whether this is going to be worth the effort involved in adding it to the entire corpus. Personally, I have rarely had problems with queries taking too long, which is what you said Agrelon would improve, whereas we have had major problems with results being confusing and not the sort of thing we can show to external researchers.

**Comment by cyocum** [comment]
> Did the new triples etc. all need to be added manually? If so, we should consider whether this is going to be worth the effort involved in adding it to the entire corpus. 

The triples are added automatically via a python script that I have written and takes very little time to run.  The ordering of the triples to match the file I have to do by hand but that also gives me the chance to review the file against what is in CELT, which I think is of some value.

> Personally, I have rarely had problems with queries taking too long, which is what you said Agrelon would improve, whereas we have had major problems with results being confusing and not the sort of thing we can show to external researchers.

I think the value here is not about the present but the future.  There are Triplestores for which using the rel ontology is _painfully_ slow.  For instance, Stardog.  I continually had problems running queries on it.  We cannot be sure what Triplestore this might be loaded into and if we can reduce the search time overall, users will want to use the data.  Otherwise, they will have queries that never finish due to timeouts and they might as well use CGH's text index.  Additionally, if this is ever hosted somewhere for others to use, users will want to have a quick query and so will anyone hosting it as multiple users querying a slow query will cripple the server for other users and render it useless.

**Comment by cyocum** [comment]
Also, you may want to use the "hide whitespace changes" which will make it much more apparent what I changed in this diff as there is more than just adding agrelon that I changed.  You can make that change using going to the File Changed tab and clicking on the cog next to the "Jump to ..." option.

**Comment by Eystein-Thanisch** [comment]
Manually re-ordering all the triples in all the files back will be **a lot** of work, especially considering that there are longer and more complex files ahead, compared to those in this sample. What do you think of my idea of creating a separate version of the corpus with Agrelon added via your Python script? That can be used for fast querying, while the other version can be the working copy for updates and periodically used to re-generate the Agrelon version.

**Comment by cyocum** [comment]
I am coming around to your way of thinking.  One of the things that I wanted out of this was more auditing as reordering the files makes you look back at the original text and re-read it.  However, you are correct that doing that would be a lot of work.  Generating the files from the python script would be very straight-forward as long as you do not care about the ordering of the files.  I will think about it some more.

**Comment by cyocum** [comment]
After thinking about it a bit, my main two thoughts are: first, we need to audit it all anyway and doing it this way both cleans up the formatting of the files and forces us to audit it; second, maintaining two separate versions is basically double the work anyway.  As I said, I am not adverse to your idea and I am preparing the Python script a bit more to be more amiable to your approach.

**Comment by Eystein-Thanisch** [comment]
I wasn't suggesting maintaining two separate versions. We would only maintain one (without Agrelon), then periodically generate another second version with Agrelon, using your Python script, which could be used for querying. There'd be no need to re-order the triples in the second version because no human would ever need to edit the .trig files there. That would all be done in the first version. Would this work or is there something I've missed? 

Auditing is very much needed, but I am not convinced it is best done by comparing individual .trig files with their source texts. Most of the errors that are emerging are to do with the identification and delineation of individuals as they exist between sources - missing or misplaced `owl:sameAs` links etc. - and these wouldn't be apparent from looking at an individual file. Viewing the results post-reasoning, such as through the Visual Graph, is far more effective. If you are aware of a significant number of counter-examples, please do flag these up. 

Finally, I simply don't have time to help significantly with a task of this scale and I think attempting it would be a drain on our morale. Thanks to your script, we can obtain a version of the database with Agrelon very easily without this being necessary.

**Pull request closed without merging**
