### PR TITLE
Section4a

### PR DESCRIPTION
**Pull request by Eystein-Thanisch**
Population group data in sections 1-4 of Rawl.B.502 is now added/up to date.

### CODE REVIEW

**Comment by cyocum** [comment]
I have merged this and I will close it now.  Please delete your local branch as there was some issues merging: there is nothing serious but I don't want to get into a tangle later.

**Comment by Eystein-Thanisch** [comment]
Oh dear. I actually just made some additional changes on Section4a. Should
I commit them to a new branch instead?

On Sun, Dec 31, 2017 at 1:13 PM, Christopher Yocum <notifications@github.com

**Comment by cyocum** [comment]
Yes, please.  I also noticed that you pushed to master which is probably why this happened (I am not entirely sure but that is my current working hypothesis).  You should:

#Take a diff of the changes that you made
# switch to master
# Pull on master 
# force delete Section4a branch
# create a new branch
# apply the diff from the first step to the new branch

I think it would be best if you do not create pull requests until you are completely finished with a branch (if that is what happened).  If you send in a pull request, I will assume that you are done then merge it, which is a fault of mine and I should stop doing that.

**Comment by Eystein-Thanisch** [comment]
Ok, will do. I did think I was finished, then noticed that a Section that I
thought was done lacked any use of the ancestorGroupOf relationship.

On Sun, Dec 31, 2017 at 1:29 PM, Christopher Yocum <notifications@github.com

**Comment by cyocum** [comment]
No problem.  Yes, git can occasionally but a bit *too* flexible :)

**Comment by Eystein-Thanisch** [comment]
One thing: on my GUI, if I switch between branches, all my unsaved commits
appear for each branch, regardless of the branch I was on when I made them.
Is this a problem (git isn't keeping my branches separate) or an
opportunity (in this instance, I can just commit to a new branch without
taking a diff etc.)?

On Sun, Dec 31, 2017 at 1:41 PM, Christopher Yocum <notifications@github.com

**Comment by cyocum** [comment]
I have no idea. The GUI that GitHub uses is really confusing to me, which is why I often have you open the command line so I can actually see what is happening, so I do not really know.  I would take the diff to be on the safest of safe sides but if things go wrong, I can probably fix it from this side.

**Comment by Eystein-Thanisch** [comment]
Right, I should come clean: how do I take a diff? :-P

On Sun, Dec 31, 2017 at 1:51 PM, Christopher Yocum <notifications@github.com

**Comment by cyocum** [comment]
It would be best if we had a Hangout and I can walk you through it.

**Pull request closed without merging**
