### PR TITLE
Laud misc610

### PR DESCRIPTION
**Pull request by Eystein-Thanisch**
Sections 1-9 of the Laud Misc 610 text, covering the northern Uí Néill in some detail.

Unfortunately, Apache Jena isn't working on my machine so syntax etc has only been checked visually.

### CODE REVIEW

**Comment by cyocum** [comment]
Running Jena on my machine, I get

```
09:03:52 ERROR riot                 :: [line: 459, col: 5 ] Keyword 'a' not legal at this point
09:03:52 ERROR riot                 :: [line: 226, col: 5 ] Triples not terminated properly: expected '.', '}' or EOF: got [KEYWORD:a]
09:03:52 ERROR riot                 :: [line: 104, col: 18] Expected IRI for predicate: got: [STRING:athúaith]
09:03:52 ERROR riot                 :: [line: 178, col: 5 ] Keyword 'a' not legal at this point
09:03:52 ERROR riot                 :: [line: 317, col: 5 ] Undefined prefix: irishrel
```

What is the error that you are getting on your machine with Jena?  If you would like, I can make the fixes and commit them to this branch.  Let me know what you think.

**Comment by Eystein-Thanisch** [comment]
It's ok, I'll put those changes through. But thanks.

The program can't find riot.bat, even though JENA_HOME is set correctly and riot.bat is definitely in the location that I specified. I'll try again later.

**Comment by Eystein-Thanisch** [comment]
`09:03:52 ERROR riot                 :: [line: 226, col: 5 ] Triples not terminated properly: expected '.', '}' or EOF: got [KEYWORD:a]
09:03:52 ERROR riot                 :: [line: 178, col: 5 ] Keyword 'a' not legal at this point`

Ok, I have corrected what I can but I can't find the locations of these errors in the files I worked on. Is there any way you can retrieve the filenames for them? Thanks.

**Comment by cyocum** [comment]
Ack! Sorry.  Here is the list with file names

```
143-10:41:18 INFO  riot                 :: File: ./Laud_Misc_610/CGH/cráeb_ceniúil_fergusa_inso.trig
144:10:41:18 ERROR riot                 :: [line: 459, col: 5 ] Keyword 'a' not legal at this point
--
147-10:41:18 INFO  riot                 :: File: ./Laud_Misc_610/CGH/cróeb_choibniusa_na_bretcha.trig
148:10:41:18 ERROR riot                 :: [line: 226, col: 5 ] Triples not terminated properly: expected '.', '}' or EOF: got [KEYWORD:a]
149-10:41:18 INFO  riot                 :: File: ./Laud_Misc_610/CGH/cróebh_choibniusa_ceniúil_feradaig_in_so.trig
150:10:41:18 ERROR riot                 :: [line: 104, col: 18] Expected IRI for predicate: got: [STRING:athúaith]
--
153-10:41:18 INFO  riot                 :: File: ./Laud_Misc_610/CGH/cróeb_cheniúil_binnig_inso.trig
154:10:41:18 ERROR riot                 :: [line: 178, col: 5 ] Keyword 'a' not legal at this point
155-10:41:18 INFO  riot                 :: File: ./Laud_Misc_610/CGH/_1.trig
156:10:41:18 ERROR riot                 :: [line: 317, col: 5 ] Undefined prefix: irishrel
```

**Comment by cyocum** [comment]
Great.  Here are a few more syntax issues for you to look at:

```
143-10:17:21 INFO  riot                 :: File: ./Laud_Misc_610/CGH/de_peritia_fhothart_so_sis.trig
144:10:17:21 ERROR riot                 :: [line: 66, col: 5 ] Triples not terminated properly: expected '.', '}' or EOF: got [KEYWORD:a]
145-10:17:21 INFO  riot                 :: File: ./Laud_Misc_610/CGH/cráeb_ceniúil_fergusa_inso.trig
146:10:17:21 ERROR riot                 :: [line: 509, col: 18] Expected IRI for predicate: got: [STRING:hi tóisigecht tes]
--
150-10:17:21 INFO  riot                 :: File: ./Laud_Misc_610/CGH/cróebh_choibniusa_ceniúil_feradaig_in_so.trig
151:10:17:21 ERROR riot                 :: [line: 606, col: 1 ] Triples not terminated properly: expected '.', '}' or EOF: got [IRI:#Cárthinn]
--
154-10:17:21 INFO  riot                 :: File: ./Laud_Misc_610/CGH/cróeb_cheniúil_binnig_inso.trig
155:10:17:21 ERROR riot                 :: [line: 389, col: 22] Expected IRI for predicate: got: [STRING:Cuac]
156-10:17:21 INFO  riot                 :: File: ./Laud_Misc_610/CGH/de_genelach_brigte.trig
157:10:17:21 ERROR riot                 :: [line: 87, col: 42] Unrecognized (expected an RDF Term): [COMMA]
158-10:17:21 INFO  riot                 :: File: ./Laud_Misc_610/CGH/_1.trig
159:10:17:21 ERROR riot                 :: [line: 742, col: 1 ] Triples not terminated properly: expected '.', '}' or EOF: got [IRI:#Domnall]
```

We probably should have a video call to see why your Jena isn't working.

**Pull request merged**
