### PR TITLE
Duplicates

### PR DESCRIPTION
**Pull request by cyocum**
This PR:

* Fixes most duplicates 
* Added a utility which attempts to identify duplicate entries
* Fixed some minor problems with the README file

The main thing to do is to check that links from Laud_Misc_610 are not effected by the changes in the PR.

### CODE REVIEW

**Comment by Eystein-Thanisch** [comment]
Or am I underestimating the power of technology? Perhaps the script can be adapted to detect links to the duplicated URI in other files?

**Comment by cyocum** [comment]
Thanks.  No, I did not even think about links between files rather than just links inside a file.  I will need to write something else to do that.  Given the volume of changes though, maybe we should accept these changes then do a "next step" trying to determine if links between files have been broken?

**Comment by Eystein-Thanisch** [comment]
It depends on what would be easiest for you to write. I was imagining adapting the existing utility so that it looks for duplicates in each file and flags up those, then looks for links to each duplicate in other files. The output would then say something like "2 duplicates seen, with 1 link in another file". We'd still have to go looking for the links elsewhere but it would speed things up (by letting us skip the ones where no links are broken).

The problem with doing it in two steps is that technically no links will be broken, there will still be the unchanged URI to which all links will now point.

**Comment by cyocum** [comment]
I think I may not be understanding you :(. If we do it in two steps, we will have broken links which at one time pointed to the now changed URL.  In this case, I would have to parse the entire database then go hunting for dead links which would then need to be fixed.  I think could be done using a triplestore or maybe something like it with some custom logic.  The side effect here would be to make the change even larger.

**Comment by Eystein-Thanisch** [comment]
But the whole point is that, of two URIs that are the same, one changes and the other does not.

For example: say we have a file called foo.trig from an ms called bar. We have mistakenly included <#Fergus> twice as a URI, referring to different people There is a link, which is meant to point to the *second* <#Fergus>, in the file fu.trig: "owl:sameAs <www.example.com/bar/foo.trig#Fergus>"

The utility changes the second URI to <#Fergus-123456789>. The link now points only to the first <#Fergus>. It is unbroken but wrong.

**Comment by cyocum** [comment]
Ah, right.  I see now, thanks. I am not sure how to fix that at the moment.  From my recollection of doing it, many of the changes had to do with different lines being confused only within the same file.  As I said, I am unsure how to fix the second problem. I will need to think about it.  We would basically need to check all incoming links into a file.

**Comment by Eystein-Thanisch** [comment]
I agree. We could do this manually, if there isn't a Perl-based solution. It will be a big task now but, in future, we will only be running the utility on new files, which obviously won't have any links to them from elsewhere. So it won't mean a lot of extra work over the long term.

**Comment by Eystein-Thanisch** [comment]
Also, to add to our troubles, I have been correcting duplicates that I have found elsewhere while working on Laud. So there is going to be a merge conflict when I try to rebase/push :-P

**Comment by cyocum** [comment]
I have had a think about this. Basically, Stardog can find all the sameAs links and I can go through them to make sure they all link the right person.  Tedious but necessary, I guess.

My suggestion about the finding duplicates while doing Laud is fix them and we will deal with the merge later.  My only caveat there is that if you find yourself fixing large amounts, we get this branch merged and then I can go look in to the sameAs problem.  How does that sound?

**Comment by cyocum** [comment]
I have gone through all the changes for de-duplicating individuals.  This should fix any missing or broken in-bound links to the files.  I have also found several other errors in the course of this and fixed those.  Have a look over it and let me know what you think.

**Pull request merged**
