### PR TITLE
Some formatting canges and new pedigrees

### PR DESCRIPTION
**Pull request by Eystein-Thanisch**
Hi Chris! Apparently there are several conflicts in this Pull Request but, having viewed them, I can't see how they are conflicts. You've added and edited some files and I have added and edited some files, that is all that seems to have happened. Anything you cand do you from your end?

### CODE REVIEW

**Comment by Eystein-Thanisch** [comment]
Update: I think I have found the problem.

**Comment by cyocum** [comment]
I have reopened this PR.  Is it ready to merge?

**Comment by Eystein-Thanisch** [comment]
I doubt it, I'm afraid. See my impending email.

**Comment by cyocum** [comment]
OK. Closed.

**Pull request closed without merging**
