### PR TITLE
Revisions

### PR DESCRIPTION
**Pull request by Eystein-Thanisch**
I made a couple of changes to tairdelbaig.ttl and, as you might be proofing it, I thought we should keep in synch.

### CODE REVIEW

**Comment by Eystein-Thanisch** [comment]
The work on sil_daimine.ttl is only partially complete, so please don't proof it just yet. I merging for the sake of some changes I made to tairdelbaig.ttl, to make sure conflicts don't develop.

**Comment by cyocum** [comment]
Ok, good idea.  Let me know when things are ready.  Exciting Friday night huh?

**Comment by Eystein-Thanisch** [comment]
Thanks! Indeed, who needs pokemon when there are dynasts to catch...

**Comment by Eystein-Thanisch** [comment]
Ok, that's Síl Daimini ready. Btw, as you already suspected, I don't think those four judges are sons of Gormlaith - the text never states as much. So shall we remove those links? Can we provide them with a professional relationship instead or should they also just be removed from the database?

**Comment by cyocum** [comment]
Hi, sorry for the delay. We could add them but just leave them unconnected to anyone.  This means that people could find them and address them from elsewhere using a link but they wouldn't be in the lineage.  What do you think?

**Comment by Eystein-Thanisch** [comment]
Ok, let's do that. Who knows? They might turn up in another pedigree.
Alternatively, I noticed this category of relationship:
http://purl.org/vocab/relationship/Relationship which I took to be the most
non-specific, general purpose form. Could we use that and relate them to
Murchad?

**Comment by cyocum** [comment]
Ok, after having a look, just using Relationship is a good idea. Do you want to do it or should I?

**Comment by cyocum** [comment]
Oops. I had a second look. The relationship you cite is actually an owl:Class which means that it is not a property of an individual. That means we cannot use that but we can use foaf:knows which is as generic as it gets (and is what the Relationship ontology depends on anyway).  Does that seem alright to you?

**Pull request merged**
